---
downloads: ~/.ansible-downloads/

vimrc_github: git@github.com:silefort/vim.git
bash_github: git@github.com:silefort/bash.git
tmux_github: git@github.com:silefort/tmux.git

# dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
# dotfiles_repo_accept_hostkey: yes
# dotfiles_repo_local_destination: ~/Dropbox/Development/GitHub/dotfiles
# dotfiles_files:
#   - .bash_profile
#   - .gitconfig
#   - .gitignore
#   - .inputrc
#   - .osx
#   - .vimrc

homebrew_installed_packages:
  - colordiff
  - dockutil
  - fzf
  - git
  - git-extras
  - jq
  - jrnl
  - pyenv
  - pyenv-virtualenvwrapper
  - reattach-to-user-namespace
  - ripgrep
  - tmux
  - tree
  - vim
  - z

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - google-backup-and-sync
  - calibre
  - cryptomator
  - brave-browser
#   - docker
  - dropbox
  - evernote
  - firefox
  - google-chrome
#   - google-drive
  - iterm2
  - keepassx
#   - lastfm
  - nextcloud
  - shiftit
  - private-internet-access
#   - slack
  - skim
  - spotify
  - standard-notes
#   - spotmenu
  - the-unarchiver
  - vagrant
  - virtualbox

dockitems_to_remove:
  - Mail
  - Contacts
  - Calendrier
  - Mission Control
  - Notes
  - Rappels
  - Plans
  - Photos
  - Photo Booth
  - Podcasts
  - Livres
  - Messages
  - FaceTime
  - iBooks
  - TV

dockitems_to_persist:
  - name: KeePassX
    path: "/Applications/KeePassX.app"
    pos: 1

  - name: Firefox
    path: "/Applications/Firefox.app"
    pos: 2

  - name: iTerm
    path: "/Applications/iTerm.app"
    pos: 3

  - name: Spotify
    path: "/Applications/Spotify.app"
    pos: 4
