---
- name: Clone bash
  git:
    repo: '{{ bash_github }}'
    dest: ~/.custom_bash

- name: Make sure Bash_profile file exists
  file:
    path: ~/.bash_profile
    state: touch

- name: Edit bash_profile
  lineinfile:
    dest: '~/.bash_profile'
    line: 'source $HOME/.custom_bash/main'

- name: Clone vimrc
  git:
    repo: '{{ vimrc_github }}'
    dest: ~/.custom_vim

- name: Install vimrc
  shell: ./install.sh
  args:
    chdir: ~/.custom_vim
  ignore_errors: yes
